### ISSUE TITLE
アイマスハッカソン2024

### ISSUE THREAD

**Issue by bode-mmk** [imas/hackathon#183]
# アイマスハッカソン2024

## 日付
- 2024/10/12(土)

## 目標参加人数
- 30

## 参加費
- 500円

## TT
- 10:00開場 20:00閉会

|時刻|内容|
|-|-|
|10:00|オープニング・スタッフ紹介・スポンサートーク|
|10:30|ハッカソン開始|
||もくもく|
|13:00|(昼休憩)|
|14:00|もくもく|
|17:00|乾杯・セッショントーク(配信開始｜食事展開完了)|
|18:00|ライトニングトーク|
|19:20|スパークトーク|
|19:50|クロージング|
|20:00|閉会|

**Comment by bode-mmk** [comment]
# アイマスハッカソン2024キックオフ

### 日時

- 2024/07/08 19:30～

## 目的

- スタッフをやろうとしている人達の顔合わせ
- ぼでーの考えていることを共有
  - 雑多に感想とかを貰って、会の解像度をメンバー間で上げていく
- 各自のスタッフロールとスケジュールの決定

## あじぇんだ

- 各自自己紹介(軽く)
- ぼでーの考えていること
- 雑多に意見もらう、皆の希望とかやりたいこととか、こういうのもっとやればいいんじゃね？とか
- スタッフの大雑把な決定をしていく
  - 主催・司会進行
    - ぼでー
  - 備品担当
    -
  - 配信・BGM
    - 
  - 食べ物・飲み物
    - 
  - 会場手配 / 会場スタッフ
    - にしこりさぶろ～
  - レクリエーション
    -

**Comment by YutaGoto** [comment]
備品など

- [ ] 名札ホルダー（持ち主: 
- [ ] 名札台紙
- [ ] ペン
- [ ] 付箋（アイディアソン用）
- [ ] カンパボックス（持ち主: XX
- [ ] 紙皿・紙（プラ）コップ・割りばし・プラフォーク（飲食
- [ ] プロジェクターにつなぐ端子（HDMI, USB-C）
- [ ]

**Comment by Shinogasa** [comment]
## 飲食周りメモ

- 前回はある程度参加人数わかってから計画
    - 実績は登録31人(スタッフ含む)
    - 参加費 500円 * 31 + 繰越 5000円 で計算
    - [検討ログ](https://github.com/imas/hackathon/blob/master/plannings/2023-05-meet-up/20230523.md#%E3%83%93%E3%82%A2%E3%83%90%E3%83%83%E3%82%B7%E3%83%A5%E3%81%AE%E9%A3%B2%E9%A3%9F%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
    - これで発注したがピザも酒も余った記憶
        - 開始が昼飯後 + バフッファ多めに頼んだ + 当日不参加何名か
- 開催にあたっての参加費と参加人数ある程度わかってから再度検討かな

**Comment by YutaGoto** [comment]
飲食周りでこういうのもありかな。 https://github.com/imas/hackathon/issues/126#issuecomment-504852134

**Comment by bode-mmk** [comment]
アイマスハッカソン2024専用のチャンネルを立てる

**Comment by bode-mmk** [comment]
# アイマスハッカソン2024キックオフ

### 日時

- 2024/08/19 19:30～

## 目的
- 現時点での決定事項の共有・各人の進捗確認
- connpassページの作成

## 議事
- 参加人数→30人目標
- 参加費500円（無銭飲食などのトラブルを極力無くしていくため）
- TT共有
- 備品周り確認
  - (コメントに追記)[https://github.com/imas/hackathon/issues/183#issuecomment-2213746078]
- 飲食周りメモ
  - (コメントに追記)[https://github.com/imas/hackathon/issues/183#issuecomment-2213803351]
- 懇親会の手配、懇親会用のconnpassのページ作成
  - 導線さんにアサイン
  - 会場周辺の候補を挙げる→店の策定→ページ作成

## TODO
- アイマスハッカソン2024専用のSlackチャンネルを立てる
- 場所等を埋めて、connpassのページを作成。スタッフにreviewページを見てもらい、OKであれば公開

## Next Action
- 9月末～10月初頭にかけて直前MTGを実施予定。（ここが実質の最終確認になる予定)

**Comment by maraigue** [comment]
## 名札について

- 「撮影不可」シールや「飲酒不可」シールを事前に用意しておくとよいかも、と思いました
  - connpassの「当日は配信にてお顔が映る場合がございます。NGの方は事前に受付にてその旨お知らせください」という記述から思い出した
  - 以前にそういうものを用意した、などはありましたでしょうか？

**Comment by Shinogasa** [comment]
前回のReburn時は配信なかったので特に何もしてませんでした
飲酒に関しても特にチェックはしてなかったので各自でって感じでした(そーいや未成年チェックもしてなかったですね……)
それ以前でも特にやってた記憶ないので各自に任せる or 名札の隅にペンでマークつけてもらうとかがコスパ良いのではって感じがします

**Comment by Shinogasa** [comment]
# 直前MTG用memo 

検討必要な事項忘れないために書き置き

## スポンサー費用いくらでしたっけ

上記ログ見ても書いてなかった
30,000円くらいだった記憶
そろそろ飲食の手配する必要あるか

## スポンサー費用の支払いは

当日現金でいただく？
飲食の費用をにしこりさんに建て替えてもらって領収書渡して精算してもらう？
注文誰がするか問題

## 打ち上げやるかどうか

そこそこ参加者いるから開催か
飲食の量は考慮する？

## 飲食検討

- 予算
  - 500 * 22 + スポンサー費用 = 11000 + a
- ピザ or ケータリング
  - 予算25000円(1200円/人)程度？
  - ケータリングは1人前1500円くらいからなので厳しいか？
- ドリンク
  -  ビール2ケース + 低アルコール + ソフドリ
  - 前回約15000円
  - ハッカソン長時間だからソフドリ多めにしておいてもよい？

**Comment by Shinogasa** [comment]
# 本当の直前MTGで確認したいこと

## 当日の流れ

ざっくりどんな感じにするか
初参加の人多そうだが、いきなり作業してねで大丈夫か？
スタッフがフォローする？

以前にはじめの人向けにオリエンテーションやアイデアソンあったかも？

ぼでーさんの頭の中になにかあるなら吐き出して欲しい

## Conpassのhackコミュ参加者にメッセージなげる

## セッショントークの順番

当日ハッカソン中に決めるでいいんじゃね？という話は出た

## その他懸念事項

あったらバシバシ出しておいてください

**Comment by bode-mmk** [comment]
振り返り #187 

参加費についてはアナゴPにAmazonギフトで送付済み
