### ISSUE TITLE
あいますえんじにあ Meetup in 京都

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#51]
## テーマ
- あいますえんじにあ Meetup in 京都

## これは何
- 関西のアイマスエンジニアで集まってはんなりしますえ～～
- 「なんでひらがな？」
  - 京都みを感じ、はんなりする為

### 日時
- 2017年9月2日(土)
- 15:00～19:00 (4時間)

### 場所
- 株式会社はてな様 京都オフィス セミナールーム
- 京都府京都市中京区高宮町御池ビル 8F

### 目標参加人数
- 15人

### 参加費
- 765円 (デレPだからミリPだからという理由で安くはならない等）

## 暫定的なタイムテーブル

|時刻|内容
|:-:|:-:|
|13:30|会場入り(スタッフ)|
|14:30|受付開始|
|15:00|開幕 - 挨拶等 (20分)|
|15:20|アイディアソン1部開始 (40分)|
|16:00|アイディアソン1部発表 (10分)|
|16:10|幕間(レクリエーション)(30分)|
|16:40|アイディアソン2部開始 (40分)|
|17:20|アイディアソン2部発表 (10分)|
|17:30|アイディアソン総括・アイディアソン締め(15分)|
|17:45|乾杯！！|
|17:50|ダイマ・愛を叫ぶLT (40分)|
|18:30|フリートークタイム (30分)|
|19:00|終幕|
|～20:00|片付け・完全撤収|

- 挨拶は正直20分も無いと思うのでそこで前倒しするのはアリ

**Comment by kaibasira** [comment]
## 会場情報
### 現在確定している情報
- プロジェクターOK
- 飲食物持ち込みOK、ピザ等もOK

### 別途確認
- [ ] 電源
- [ ]  Wi-fi情報
- [ ] ホワイトボード(一応)
- [ ] ポスター・フィギュア等の飾り付けの可否
- [ ] 行き方 / ルートマップ等あるか？(迷子を防ぐ)
- [ ] 会場内での写真撮影の可否
- [ ] コールの可否
- [ ] ゴミの処理 / こちらで袋を用意するのか、会場でゴミ箱を提供してもらえるのか
- [ ] 音響の確認 / ミキサの使用可否等
- [ ] 生放送の可否
- [ ] その他じゅりあす様から追加確認事項あれば別途確認

### TODO:
- じゅりあすさんとのオフミーティング / 会場確認
  - できれば8月最初の方の週末ぐらい

**Comment by kaibasira** [comment]
## イベント内容情報
### 当日の企画内容
- アイディアソンについて
  - 4～5人グループを3つ作る
  - 予め、幾つかの技術テーマやプログラミング言語・ライブラリを記述したワードカードを用意しておく (ex. 「機械学習」「C++」「SQL」……等)
  - また、アイマスに関係するワードカードも用意しておく(ex. 「キュート属性のアイドル」「京都出身のアイドル」……等)
  - それらのワードカードについて幾つかを選択してもらい、１つのテーマとして成立させる
  - それに対して、アプローチや具体的な実装を議論してもらう
  - モチロン自分たちで自由にワードを書き込めるフリーワードカードもアリ
  - 最終的に発表タイムで発表
  - 第1部はtech要素ワードカード多め、第2部は『アイドルを愛でる』要素ワードカード多め
- レクリエーションについて
  - アイマスドン、もしくはアイドルの出身地言えるかな？とか（笑）
  - これについては誰かに任せるかもしれない（
- 愛を叫ぶLT
  - 前回と同じく、担当アイドルの布教活動の場を提供する
  - モチロンここでアイマスハック的な成果発表もアリ
  - とにかく自由にアイドルについて語ってもらおう
- フリートークタイム
  - LT後ブレーキング、皆でフリーに自由に交流する
  - ~~ぼでーが皆と絡みたいだけ~~

### 当日までの企画・宣言・告知
- 前回に引き続き会場で流す曲の募集を行う
  - Slack / #generalチャンネルで募集
  - Twitter / #imas_hack, #imas_hack_kyoto つけて貰う
- (飾り付けOKなら)会場で飾り付けたい物品を提供してもらう
  - 曲の募集と同上
- ちひろさんカンパBOX
  - 「回さなきゃでねぇ」
- (会場内撮影OKなら)カメラマンを決める
  - 最後集合写真撮りたい
- 今回はお菓子を持ち寄りしてもらおうという考え

### ノベルティ
- サイリウム(仮)
- 他何か考えるか……？

### ニコ生について
- 今回はチャレンジ！！！！！(但し配信OKかどうか会場確認)
- 試験的にリスナー一体型アイディアソンを目指す
- アイディアソン時
  - 主コメで「ワードカード」のURLを貼っておく (githubとかになると思う)
  - リスナー同士、もしくはリスナーに考えてもらったアイディアを自由にコメントで投稿してもらう
  - 頑張って収集して反応する それを逐次会場のメンバーで議論してみるのもアリ
- レクリエーション
  - コメントで答え言ってもらうのもアリ（もちろん会場のメンバーに開示はしない - カンニングは善意に委ねるｗ)
- フリートークタイム
  - 適当にコメント拾う
  - アイマスハッカソン2016の時みたいな感じ
- TODO: カメラやマイク、後はニコ生配信専用のキーパーが欲しい

**Comment by kaibasira** [comment]
## スタッフ's TODO
### ぼでー's Task
- [ ] connpass、ATND、dotsでの告知案の作成 (～8/4)
- [ ] 告知 (8/6)
- [ ] 告知後、Readmeに開催中イベント記述しPR
- [ ] ワードカードの内容を考える

### 現状スタッフ( 敬称略、HN )
- ぼでー
- cromisa
- うろうP
- もめん
- ......後2人は欲しいかもしれない 間に合わそうだったら来れる人に無茶ぶる（

### 役割分担等
- ref. #44

**Comment by adachi-tsukasa** [comment]
みんな担当家を感じるのかよ……
> 櫻井家は十分に感じすぎている

これはおかしい

**Comment by kaibasira** [comment]
## 食事の段取り決める通話MTG
### Agenda

### 参加者
- ぼでー
- もめん

### 目的
- みーとあっぷ当日の飲食物の流れ、準備物の概要決定
- ネタおやつの選定

### 会場状況
- ピザ宅配OK
- お菓子の持ち寄りもOK

### ref
- https://github.com/imas/hackathon/blob/master/plannings/20170202.md

### 飲食物の動きTL

|時刻|内容|おかしな国の動き|
|:-:|:-:|:-:|
|13:30|会場入り(スタッフ)|特になし(必要あれば買い出し内容の確認)|
|14:30|受付開始|様子を見てテーブルに飲み物提供|
|15:00|開幕 - 挨拶等 (20分)|持ち寄りのお菓子で持たせる|
|15:20|アイディアソン1部開始 (40分)|↓（ここまで持たせる）|
|16:00|アイディアソン1部発表 (10分)|お菓子の様子見て補充してください|
|16:10|幕間(レクリエーション)(30分)|↓|
|16:40|アイディアソン2部開始 (40分)|お菓子、飲み物補填、出来たらここはネタ極めていきたい|
|17:20|アイディアソン2部発表 (10分)|↓|
|17:30|アイディアソン総括・アイディアソン締め(15分)|お酒、飲食物、ピザの用意等|
|17:45|乾杯！！|乾杯！！|
|17:50|ダイマ・愛を叫ぶLT (40分)|飲み物とかはセルフで良さそう|
|18:30|フリートークタイム (30分)|頃合いを見て空いてるお菓子や余ったジュースなど適当に配ったりしてください|
|19:00|終幕|ごみ収集|
|～20:00|片付け・完全撤収|撤収|

### 準備物
- お菓子
  - 人数によるが、今回は持ち寄りをお願いするのでアイディアソン2部開始時のネタおやつに重きをおく
  - 要、ネタおやつ考える 京都み
- 飲み物
  - まだ残暑も厳しいだろうし前回のを見てると割と要る気がする
  - 前回何本買ったんでしたっけ～ど忘れしてしまった＞＜
  - 人×2L+お酒ぐらいかな？もっと要る？
- 乾杯後のくいもん
  - ピザかなぁ？お金の面もあるので通話中にどうするか決めましょう
  - TOKYO Meetup時の枚数のノウハウを教えてください
- ナプキン等の段取り
  - お手拭きやティッシュ等は開封して使える状態でおいておこう（前回KPTより）
  - 各テーブル（全部で3つグループ予定)1セットずつあればいいかな？
- 食事時の段取り
  - 乾杯時にはテーブルをのけてもらう
  - つまり17:45以降は終幕まで立食形式

### 追加確認
- 近くのピザ屋 (ぼでー→じゅりあすさんに知ってたら教えてもらう)

### その他必要事項
- 通話中思い浮かべば確認
- archive
  - 恐らくいつも通りぼでーが桃華駅から家までの途中、って感じになるのでもめんさんお願いします。。。
  - まとまり後、PR投げてもらって私＋スタッフ1人（もしくはtrebyさん)にapprovedかslackで確認したよアクション貰ったらマージしちゃいます

**Comment by treby** [comment]
MTG議事録待機

**Comment by adachi-tsukasa** [comment]
この間MTGできず、リスケ中です…

**Comment by kaibasira** [comment]
## 2017/08/18 通話Kick offのアジェンダ
### やること
- 軽い自己紹介
- 各位のやることの再確認・TODOの摺合せ
   - スタッフ's TODO
- ネタ的なおやつを挙げてみる
- その他確認事項

**Comment by kaibasira** [comment]
## 2017/08/28 通話確認のアジェンダ
### やること
- 当日のざっとスケジュール確認
- imasparqlでやること考える
- その他雑多に確認

**Comment by hamup8** [comment]
## 必要雑貨
- [ ] ティッシュ
- [ ] ウェットティッシュ
- [ ] 紙皿
- [ ] 紙コップ
- [ ] マスキングテープ
- [ ] ドラのようなもの(ドラがなければ)
- [ ] 雑巾・布巾？（前回はお酒とか回収した時、多少床にこぼれたりしていたので）
- [ ] 名札入れ
- [ ] 名札
- [ ] ペン
- [ ] 物理ジュエル的な何か？
- [ ] ちょっとしたホワイトボード(前回も各チームのアイデアまとめた時に使ってた気が)
- [ ] ゴミ袋

**Comment by urou** [comment]
テスト

**Comment by adachi-tsukasa** [comment]
@hamup8 ペーパータオル（1箱）、ウェットティッシュ（2箱）、紙コップ（20個）、ゴミ袋（45L×15袋ぐらい）、マスキング（2巻）あります。こちらから持っていく前提で良いですかね…？

**Comment by hamup8** [comment]
@adachi-tsukasa おお...！すみませんがお願いしてもいいですか？

**Comment by adachi-tsukasa** [comment]
@hamup8 了解です！持っていきますね。

**Comment by adachi-tsukasa** [comment]
## 飲み物・食べ物について
前日になってしまいましが、ご報告します。

### 用意・提供時間
 - 飲み物、菓子類
東京肉上げのように1箇所にまとめず、各テーブルに提供。
アルコールは乾杯のタイミング(17:45)に提供。

 - ピザ
提供時間はbodeさんがアップしているタイムスケジュールに沿って、17:30頃提供。

### 注文済み、予定の品々
https://sue445.github.io/pizza-beer/
でスタッフ含めた15人、を想定し、見積もってみました。

 - 飲み物、菓子類
ビール、チューハイ等アルコール：350ml×25本 = 4500円
ソフトドリンク：1.5l×3本 = 750円
 菓子類：1500円

 - ピザ（注文済み）
13611円/5枚

**合計：15111円**

**Comment by kaibasira** [comment]
- ワードカード ref #63
